version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ENV_RedisHost: "redis"
    ports:
      - 8089:80
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - 6379:6379
